// File generated by Gambit v4.9.3
// Link info: (409003 (js ()) "libphp" (("libphp")) (module_register peps make_interned_symbol ffi pair r2 glo-println glo poll pollcount string r1 r0 sp stack wrong_nargs nargs) (println append alert for-each app# current-milliseconds) (println append alert for-each libphp# current-milliseconds) (println append alert for-each current-milliseconds) #f)

g_cst0_G_libphp = new G_ScmString([62,62,62,32,108,105,98,112,104,112,46,115,99,109]);

g_bb1_libphp_23_ = function () { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb1_libphp_23_);
  }
  g_stack[g_sp+1] = g_r0;
  g_r1 = g_cst0_G_libphp;
  ++g_sp;
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_libphp_23_);
  } else {
    g_r0 = g_bb3_libphp_23_;
    g_nargs = 1;
    return g_glo["println"]();
  }
};


g_bb1_libphp_23_.id = 0;
g_bb1_libphp_23_.parent = g_bb1_libphp_23_;
g_bb1_libphp_23_.nfree = -1;
g_bb1_libphp_23_._name = g_make_interned_symbol("libphp#");
g_bb1_libphp_23_.ctrlpts = null;
g_bb1_libphp_23_.info = false;

g_bb2_libphp_23_ = function () {
  g_r0 = g_bb3_libphp_23_;
  g_nargs = 1;
  return g_glo["println"]();
};


g_bb2_libphp_23_.id = 1;
g_bb2_libphp_23_.parent = g_bb1_libphp_23_;

g_bb3_libphp_23_ = function () { // return-point
  g_glo["for-each"] = g_bb1_for_2d_each;
  g_glo["append"] = g_bb1_append;
  g_glo["current-milliseconds"] = g_bb1_current_2d_milliseconds;
  g_glo["alert"] = g_bb1_alert;
  g_r0 = g_stack[g_sp];
  if (--g_pollcount === 0) {
    return g_poll(g_bb4_libphp_23_);
  } else {
    g_nargs = 0;
    --g_sp;
    return g_glo["app#"]();
  }
};


g_bb3_libphp_23_.id = 2;
g_bb3_libphp_23_.parent = g_bb1_libphp_23_;
g_bb3_libphp_23_.fs = 1;
g_bb3_libphp_23_.link = 1;

g_bb4_libphp_23_ = function () {
  g_nargs = 0;
  --g_sp;
  return g_glo["app#"]();
};


g_bb4_libphp_23_.id = 3;
g_bb4_libphp_23_.parent = g_bb1_libphp_23_;


g_bb1_libphp_23_.ctrlpts = [g_bb1_libphp_23_,g_bb2_libphp_23_,g_bb3_libphp_23_,g_bb4_libphp_23_];


g_peps["libphp#"] = g_bb1_libphp_23_;
g_glo["libphp#"] = g_bb1_libphp_23_;

g_bb1_for_2d_each = function () { // entry-point
  if (g_nargs !== 2) {
    return g_wrong_nargs(g_bb1_for_2d_each);
  }
  if (g_r2 instanceof G_Pair) {
    g_stack[g_sp+1] = g_r0;
    g_stack[g_sp+2] = g_r1;
    g_stack[g_sp+3] = g_r2;
    g_r1 = g_r2.car;
    g_sp += 3;
    if (--g_pollcount === 0) {
      return g_poll(g_bb3_for_2d_each);
    } else {
      g_r0 = g_bb4_for_2d_each;
      g_nargs = 1;
      return g_stack[g_sp-1]();
    }
  } else {
    g_r1 = void 0;
    return g_r0;
  }
};


g_bb1_for_2d_each.id = 0;
g_bb1_for_2d_each.parent = g_bb1_for_2d_each;
g_bb1_for_2d_each.nfree = -1;
g_bb1_for_2d_each._name = g_make_interned_symbol("for-each");
g_bb1_for_2d_each.ctrlpts = null;
g_bb1_for_2d_each.info = false;

g_bb2_for_2d_each = function () {
  g_stack[g_sp+1] = g_r0;
  g_stack[g_sp+2] = g_r1;
  g_stack[g_sp+3] = g_r2;
  g_r1 = g_r2.car;
  g_sp += 3;
  if (--g_pollcount === 0) {
    return g_poll(g_bb3_for_2d_each);
  } else {
    g_r0 = g_bb4_for_2d_each;
    g_nargs = 1;
    return g_stack[g_sp-1]();
  }
};


g_bb2_for_2d_each.id = 1;
g_bb2_for_2d_each.parent = g_bb1_for_2d_each;

g_bb3_for_2d_each = function () {
  g_r0 = g_bb4_for_2d_each;
  g_nargs = 1;
  return g_stack[g_sp-1]();
};


g_bb3_for_2d_each.id = 2;
g_bb3_for_2d_each.parent = g_bb1_for_2d_each;

g_bb4_for_2d_each = function () { // return-point
  g_r2 = g_stack[g_sp].cdr;
  g_r1 = g_stack[g_sp-1];
  g_r0 = g_stack[g_sp-2];
  if (--g_pollcount === 0) {
    return g_poll(g_bb5_for_2d_each);
  } else {
    g_nargs = 2;
    g_sp -= 3;
    return g_glo["for-each"]();
  }
};


g_bb4_for_2d_each.id = 3;
g_bb4_for_2d_each.parent = g_bb1_for_2d_each;
g_bb4_for_2d_each.fs = 3;
g_bb4_for_2d_each.link = 1;

g_bb6_for_2d_each = function () {
  g_r1 = void 0;
  return g_r0;
};


g_bb6_for_2d_each.id = 4;
g_bb6_for_2d_each.parent = g_bb1_for_2d_each;

g_bb5_for_2d_each = function () {
  g_nargs = 2;
  g_sp -= 3;
  return g_glo["for-each"]();
};


g_bb5_for_2d_each.id = 5;
g_bb5_for_2d_each.parent = g_bb1_for_2d_each;


g_bb1_for_2d_each.ctrlpts = [g_bb1_for_2d_each,g_bb2_for_2d_each,g_bb3_for_2d_each,g_bb4_for_2d_each,g_bb6_for_2d_each,g_bb5_for_2d_each];


g_peps["for-each"] = g_bb1_for_2d_each;

g_bb1_append = function () { // entry-point
  if (g_nargs !== 2) {
    return g_wrong_nargs(g_bb1_append);
  }
  if (g_r1 instanceof G_Pair) {
    g_stack[g_sp+1] = g_r0;
    g_stack[g_sp+2] = g_r1;
    g_r1 = g_r1.cdr;
    g_sp += 2;
    if (--g_pollcount === 0) {
      return g_poll(g_bb3_append);
    } else {
      g_r0 = g_bb4_append;
      g_nargs = 2;
      return g_glo["append"]();
    }
  } else {
    g_r1 = g_r2;
    return g_r0;
  }
};


g_bb1_append.id = 0;
g_bb1_append.parent = g_bb1_append;
g_bb1_append.nfree = -1;
g_bb1_append._name = g_make_interned_symbol("append");
g_bb1_append.ctrlpts = null;
g_bb1_append.info = false;

g_bb2_append = function () {
  g_stack[g_sp+1] = g_r0;
  g_stack[g_sp+2] = g_r1;
  g_r1 = g_r1.cdr;
  g_sp += 2;
  if (--g_pollcount === 0) {
    return g_poll(g_bb3_append);
  } else {
    g_r0 = g_bb4_append;
    g_nargs = 2;
    return g_glo["append"]();
  }
};


g_bb2_append.id = 1;
g_bb2_append.parent = g_bb1_append;

g_bb3_append = function () {
  g_r0 = g_bb4_append;
  g_nargs = 2;
  return g_glo["append"]();
};


g_bb3_append.id = 2;
g_bb3_append.parent = g_bb1_append;

g_bb4_append = function () { // return-point
  g_r2 = g_stack[g_sp].car;
  g_r1 = new G_Pair(g_r2,g_r1);
  g_sp -= 2;
  return g_stack[g_sp+1]();
};


g_bb4_append.id = 3;
g_bb4_append.parent = g_bb1_append;
g_bb4_append.fs = 2;
g_bb4_append.link = 1;

g_bb5_append = function () {
  g_r1 = g_r2;
  return g_r0;
};


g_bb5_append.id = 4;
g_bb5_append.parent = g_bb1_append;


g_bb1_append.ctrlpts = [g_bb1_append,g_bb2_append,g_bb3_append,g_bb4_append,g_bb5_append];


g_peps["append"] = g_bb1_append;

g_bb1_current_2d_milliseconds = function () { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb1_current_2d_milliseconds);
  }
  g_r1 = Date.now();
  return g_r0;
};


g_bb1_current_2d_milliseconds.id = 0;
g_bb1_current_2d_milliseconds.parent = g_bb1_current_2d_milliseconds;
g_bb1_current_2d_milliseconds.nfree = -1;
g_bb1_current_2d_milliseconds._name = g_make_interned_symbol("current-milliseconds");
g_bb1_current_2d_milliseconds.ctrlpts = null;
g_bb1_current_2d_milliseconds.info = false;


g_bb1_current_2d_milliseconds.ctrlpts = [g_bb1_current_2d_milliseconds];


g_peps["current-milliseconds"] = g_bb1_current_2d_milliseconds;

g_bb1_alert = function () { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_alert);
  }
  echo(g_scm2host(g_r1));
  g_r1 = void 0;
  return g_r0;
};


g_bb1_alert.id = 0;
g_bb1_alert.parent = g_bb1_alert;
g_bb1_alert.nfree = -1;
g_bb1_alert._name = g_make_interned_symbol("alert");
g_bb1_alert.ctrlpts = null;
g_bb1_alert.info = false;


g_bb1_alert.ctrlpts = [g_bb1_alert];


g_peps["alert"] = g_bb1_alert;

g_module_register([[g_make_interned_symbol("libphp")],[],null,1,g_bb1_libphp_23_,false]);

